### PR TITLE
dws_cluster module

### PR DESCRIPTION
**Pull request by vineet-pruthi**
DWS Cluster module

### CODE REVIEW

**Comment by anton-sidelnikov** [comment]
Hi @vineet-pruthi please update version also in https://github.com/opentelekomcloud/ansible-collection-cloud/blob/main/galaxy.yml for release

**Comment by vineet-pruthi** [comment]
> Hi @vineet-pruthi please update version also in https://github.com/opentelekomcloud/ansible-collection-cloud/blob/main/galaxy.yml for release

Hi @anton-sidelnikov  Update version -> 0.14.4 in galaxy.yml

**Comment by vineet-pruthi** [comment]
recheck

**Review by anton-sidelnikov — APPROVED** [review]

**Comment by vineet-pruthi** [comment]
recheck

**Pull request merged**
