### PR TITLE
Update galaxy.yml release version

### PR DESCRIPTION
**Pull request by anton-sidelnikov**
Need for release

### CODE REVIEW

**Review by vladimirhasko — DISMISSED** [review]

**Comment by vladimirhasko** [comment]
regate

**Comment by anton-sidelnikov** [comment]
regate

**Comment by anton-sidelnikov** [comment]
regate

**Review by Aloento — APPROVED** [review]

**Review by Aloento — APPROVED** [review]

**Review by artem-lifshits — APPROVED** [review]

**Review by Aloento — APPROVED** [review]

**Comment by vladimirhasko** [comment]
recheck

**Pull request merged**
