### PR TITLE
Small fix for dnat rule 

### PR DESCRIPTION
**Pull request by Polina-Gubina**
Small fix for dnat rule

### CODE REVIEW

**Comment by Polina-Gubina** [comment]
recheck

**Review by tischrei — APPROVED** [review]

**Review by anton-sidelnikov — APPROVED** [review]

**Comment by Polina-Gubina** [comment]
recheck

**Comment by Polina-Gubina** [comment]
recheck

**Comment by Polina-Gubina** [comment]
recheck

**Comment by Polina-Gubina** [comment]
recheck

**Comment by Polina-Gubina** [comment]
recheck

**Pull request merged**
