### PR TITLE
update test requirements

### PR DESCRIPTION
**Pull request by gtema**

### CODE REVIEW

**Review by vladimirvshivkov — APPROVED** [review]

**Comment by gtema** [comment]
ups, quite lot to fix now

**Comment by gtema** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
2022-06-06 07:25:22.899208 | RUN END RESULT_TIMED_OUT: [untrusted : github.com/opentelekomcloud-infra/otc-zuul-jobs/playbooks/ansible-test-base/run.yaml@master]

**Review by anton-sidelnikov — APPROVED** [review]

**Comment by kucerakk** [comment]
recheck

**Pull request merged**
